Add support for non nonconservative equations to subcell-limiting
bennibolm/Trixi.jl pull request #116
Opened 2023-10-13 16:55 UTC by amrueda

2023-10-17 11:39 UTC, bennibolm requested changes
In general, this looks good to me. I've just added some smaller comments.

2023-10-17 11:39 UTC, bennibolm commented on examples/tree_2d_dgsem/elixir_mhd_shockcapturing_subcell.jl
> +                                bar_states = false)
```suggestion
                                positivity_variables_nonlinear=[pressure],
                                positivity_correction_factor=0.1,
                                bar_states=false)
```
I would keep this consistent.
I know the JuliaFormatter would use white spaces here:), but we can change this in the future if the format is used for elixirs.

2023-10-17 11:39 UTC, bennibolm commented on src/equations/equations.jl
> +"""
```suggestion

"""
```

2023-10-17 11:39 UTC, bennibolm commented on src/equations/equations.jl
> +"""
```suggestion

"""
```

2023-10-17 11:39 UTC, bennibolm commented on src/equations/equations.jl
> +struct NonConservativeSymmetric end
```suggestion
struct NonConservativeSymmetric end

```

2023-10-17 11:39 UTC, bennibolm commented on src/equations/ideal_glm_mhd_2d.jl
> +@inline function isValidState(cons, equations::IdealGlmMhdEquations2D)
```suggestion
@inline function is_valid_state(cons, equations::IdealGlmMhdEquations2D)
```
I changed this in the last PR. Sorry.

2023-10-17 11:39 UTC, bennibolm commented on src/equations/ideal_glm_mhd_2d.jl
> +
```suggestion
@inline function pressure(u, equations::IdealGlmMhdEquations2D, derivative::True)
    return dpdu(u, equations)
end

```
Probably, it would be best to add a general function to `equations.jl` instead of adding it for every equation, right? Does it contain the same parameter for every equation?

The same holds for the both entropy variable routines.

2023-10-17 11:39 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
>      A3dp1_y = Array{uEltype, 3}
Did you find out something about this? Is it necessary? Either way, we should keep it here and change it somewhere else.

2023-10-17 11:39 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +    end
```suggestion
calcflux_fhat!(fhat1_L, fhat1_R, fhat2_L, fhat2_R, u, mesh,
               nonconservative_terms, equations, volume_flux_dg, dg, element,
               cache)
```
In the past, I had some issues using a timer here when using more threads, since this function is called in parallel per element. Did you try this and got no problems?

Also for the other timers.

2023-10-17 11:39 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +# Calculate the DG staggered volume fluxes `fhat` in subcell FV-form inside the element
```suggestion

# Calculate the DG staggered volume fluxes `fhat` in subcell FV-form inside the element
```

2023-10-17 11:39 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +    end
```suggestion
    end
    
```

2023-10-17 11:39 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +# Calculate the antidiffusive flux `antidiffusive_flux` as the subtraction between `fhat` and `fstar` for conservative systems.
```suggestion

# Calculate the antidiffusive flux `antidiffusive_flux` as the subtraction between `fhat` and `fstar` for conservative systems.
```

2023-10-17 11:39 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +            antidiffusive_flux1_R[v, i, j, element] = antidiffusive_flux1_L[v, i, j,
Did you try how much slower a simulation with no non-conservative terms gets when use the difference for `_L` and `_R`. Then, we could spare one of these two functions, right?

2023-10-17 11:39 UTC, bennibolm commented on src/callbacks_stage/bounds_check_2d.jl
> +                              time, iter, output_directory, save_errors, interval) # TODO: nonconservative_terms::False
Does this make a difference for the bound check routine?

2023-10-17 11:42 UTC, amrueda commented on src/callbacks_stage/bounds_check_2d.jl
> +                              time, iter, output_directory, save_errors, interval) # TODO: nonconservative_terms::False
MCL is not working for non-conservative terms. Tbh, I don't know how to compute the non-conservative MCL fluxes.. So this is for the future. If you want, I can remove the TODO.

2023-10-17 11:43 UTC, amrueda commented on examples/tree_2d_dgsem/elixir_mhd_shockcapturing_subcell.jl
> +                                bar_states = false)
That's fine for me.. However, will this cause the new Trixi format tests to fail?

2023-10-17 11:44 UTC, amrueda commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +            antidiffusive_flux1_R[v, i, j, element] = antidiffusive_flux1_L[v, i, j,
I didn't test but maybe it makes sense.. It's anyway just a subtraction.

2023-10-17 11:49 UTC, bennibolm commented on src/callbacks_stage/bounds_check_2d.jl
> +                              time, iter, output_directory, save_errors, interval) # TODO: nonconservative_terms::False
Yes, I saw that `calc_antidiffusive_limited!()` is just defined for `nonconservative_terms=False`. No, we can keep this.

2023-10-17 11:52 UTC, bennibolm commented on examples/tree_2d_dgsem/elixir_mhd_shockcapturing_subcell.jl
> +                                bar_states = false)
No, the tests only focus on the src files. I don't know if it is the plan to change this in the future, but then we would have to change much more as indentation, double empty lines...

2023-10-17 11:58 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +            antidiffusive_flux1_R[v, i, j, element] = antidiffusive_flux1_L[v, i, j,
Or maybe we just keep it and wait what the others say in the other PR.

2023-10-20 14:52 UTC, amrueda commented on src/equations/ideal_glm_mhd_2d.jl
> +
Well, maybe we can remove dpdu and just keep `pressure(u, equations::IdealGlmMhdEquations2D, derivative::True)`?

2023-10-20 14:54 UTC, amrueda commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
>      A3dp1_y = Array{uEltype, 3}
I don't think it's necessary.

2023-10-20 14:54 UTC, amrueda commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +    end
True.. This was just for debugging in the other PR. Thanks!

2023-10-20 14:55 UTC, amrueda commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +    end
```suggestion
    calcflux_fv!(fstar1_L, fstar1_R, fstar2_L, fstar2_R, u, mesh,
                 nonconservative_terms, equations, volume_flux_fv, dg, element,
                 cache)
```

2023-10-20 14:56 UTC, amrueda commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
> +    end
```suggestion
    calcflux_antidiffusive!(fhat1_L, fhat1_R, fhat2_L, fhat2_R,
                            fstar1_L, fstar1_R, fstar2_L, fstar2_R,
                            u, mesh, nonconservative_terms, equations, limiter, dg,
                            element, cache)
```

2023-10-23 08:19 UTC, bennibolm commented on src/equations/ideal_glm_mhd_2d.jl
> +
Yes, we can do that:+1:

2023-10-23 08:20 UTC, bennibolm commented on src/solvers/dgsem_tree/dg_2d_subcell_limiters.jl
>      A3dp1_y = Array{uEltype, 3}
Okay. You can keep it as it is in this PR. I will open another one for this.

2023-10-23 10:31 UTC, amrueda commented on src/equations/ideal_glm_mhd_2d.jl
> +
Done in baeaf029

2023-10-23 11:52 UTC, bennibolm commented on src/equations/ideal_glm_mhd_2d.jl
> +
Could you please do the same for `CompressibleEulerEquations2D`?

2023-10-23 13:23 UTC, amrueda commented on src/equations/ideal_glm_mhd_2d.jl
> +
Done in 342bf608

2023-10-23 13:30 UTC, bennibolm commented on src/equations/ideal_glm_mhd_2d.jl
> +
Thanks

2023-10-31 10:13 UTC, bennibolm approved these changes

2023-10-31 15:25 UTC, bennibolm commented on test/test_tree_2d_eulermulti.jl
> +end
```suggestion
@trixi_testset "elixir_eulermulti_shock_bubble_shockcapturing_subcell_minmax.jl" begin
    @test_trixi_include(joinpath(EXAMPLES_DIR,
                                 "elixir_eulermulti_shock_bubble_shockcapturing_subcell_minmax.jl"),
                        l2=[
                            76.59096367977872,
                            1.9879932386864356,
                            59851.34515039375,
                            0.18710988181124935,
                            0.010631432251136084,
                        ],
                        linf=[
                            212.71245739310544,
                            27.399221359958894,
                            158389.9681231281,
                            0.6524718882809865,
                            0.10630137919864985,
                        ],
                        initial_refinement_level=3,
                        tspan=(0.0, 0.001))
    # Ensure that we do not have excessive memory allocations
    # (e.g., from type instabilities)
    let
        t = sol.t[end]
        u_ode = sol.u[end]
        du_ode = similar(u_ode)
        @test (@allocated Trixi.rhs!(du_ode, u_ode, semi, t)) < 15000
    end
end
```

2023-11-02 10:50 UTC, merged